"""add thumbnail_url to spots

Revision ID: 256bb5c229a5
Revises: 9cb4716d2d82
Create Date: 2025-08-24 16:48:57.303903

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '256bb5c229a5'
down_revision = '9cb4716d2d82'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('spots', schema=None) as batch_op:
        batch_op.add_column(sa.Column('thumbnail_url', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('spots', schema=None) as batch_op:
        batch_op.drop_column('thumbnail_url')

    # ### end Alembic commands ###
