"""add thumbnail_filename to spots

Revision ID: 5c695a566191
Revises: 256bb5c229a5
Create Date: 2025-08-24 21:15:08.066255

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5c695a566191'
down_revision = '256bb5c229a5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('spots', schema=None) as batch_op:
        batch_op.add_column(sa.Column('thumbnail_filename', sa.String(length=512), nullable=True))
        batch_op.drop_column('thumbnail_url')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('spots', schema=None) as batch_op:
        batch_op.add_column(sa.Column('thumbnail_url', sa.VARCHAR(length=255), nullable=True))
        batch_op.drop_column('thumbnail_filename')

    # ### end Alembic commands ###
